project:
  type: website
  output-dir: docs

website:
  title: "DBER.xyz"
  site-url: https://www.dber.xyz
  description: "DBER.xyz"
  navbar:
    background: "#000000"
    pinned: TRUE
    favicon: /assets/logo_150_x_150.png
    right:
      - text: Home
        href: index.qmd
  body-footer: |
    </br></br>
    Copyright 2023, Jeffrey R. Raker. </br>
    Content is available under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license unless otherwise noted.

format:
  html:
    theme: darkly
    css: styles.css

editor: visual

