project:
  type: website
  output-dir: docs

website:
  title: "DBER.xyz"
  site-url: https://www.dber.xyz
  description: "DBER.xyz"
  navbar:
    background: "#000000"
    pinned: TRUE
    right:
      - text: Home
        href: index.qmd

format:
  html:
    theme: darkly
    css: styles.css

editor: visual

